org: upstandfm
app: api
service: audio-transcoder

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  cfnRole: ${secrets:CFN_ROLE_ARN}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: upstandfm-deployments
    serverSideEncryption: AES256 # when using server-side encryption
  environment:
    # Reuse TCP connection to reduce request latency
    # For more info see:
    # https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24630
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    # AWS Elastic Transcoder is not available in all regions
    ELASTIC_TRANSCODER_REGION: eu-west-1
    # The ARN has the format "arn:aws:elastictranscoder:::pipeline/pipelineId"
    # Splitting on "/" gives us the pipeline ID
    TRANSCODE_AUDIO_RECORDINGS_PIPELINE_ID:
      'Fn::Select':
        [
          '1',
          {
            'Fn::Split':
              ['/', '${secrets:TRANSCODE_AUDIO_RECORDINGS_PIPELINE_ARN}'],
          },
        ]
    # The ARN has the format "arn:aws:elastictranscoder:::preset/presetId"
    # Splitting on "/" gives us the preset ID
    TRANSCODER_AAC_64_PRESET_ID:
      'Fn::Select':
        [
          '1',
          {
            'Fn::Split': ['/', '${secrets:TRANSCODER_PRESET_AUDIO_AAC_64_ARN}'],
          },
        ]
    TRANSCODER_AAC_64_PRESET_FILE_EXTENSION: m4a

  # See: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html
  iamRoleStatements:
    - Effect: Allow
      Action:
        - elastictranscoder:CreateJob
      Resource:
        - ${secrets:TRANSCODE_AUDIO_RECORDINGS_PIPELINE_ARN}
        - ${secrets:TRANSCODER_PRESET_AUDIO_AAC_64_ARN}
        - ${secrets:TRANSCODER_PRESET_AUDIO_AAC_128_ARN}
        - ${secrets:TRANSCODER_PRESET_AUDIO_MP3_128_ARN}

package:
  exclude:
    - ./*
    - ./**/*.test.js
  include:
    - node_modules
    - src

functions:
  elasticTranscoderToM4a:
    handler: src/elastic-transcoder.convertToM4a
    decription: Schedules an AWS Elastic Transcoder job to convert an audio recording into m4a
    events:
      - sns: ${state:infra.newS3AudioRecordingTopicArn}
